# drugs_list and urls_json were partially changed

drugs_list = ["Нурофен 200мг №10", "Но-шпа 40мг №60", "Нимесулид 100мг №20", "Спазмалгон №50", "Панадол 500мг №12 таб раств", "Кетанов 10мг №100", "Фастум гель 2,5% 50г", "Корвалол №20", "Ново-пассит 100мл", "Афобазол 10мг №60", "Терафлю лимон №4", "Стрепсилс мед лимон №24", "Гексорал 0,2% 40мл", "Назонекс 50мкг 60доз", "Пиносол капли 10мл", "Синекод 1,5мг 100мл сироп", "Амбробене сироп 15мг/5мл 100мл", "АЦЦ 200мг №20 таб шип", "Супрастин 25мг №20", "Кларитин 10мг №10", "Тавегил 1мг №10", "Фестал №20 драже", "Мезим форте №20", "Смекта 3г №10 ваниль", "Линекс капс №16", "Фосфалюгель 16г №6", "Эспумизан 40мг №50", "Имодиум 2мг №10 лиоф", "Сенаде 13,5мг №500", "Бепантен мазь 5% 30г", "Банеоцин мазь 20г", "Найз гель 1% 20г"]

stores_list = ["Самсон Фарма", "Неофарм", "Асна", "Eapteka", "Аптека 36.6", "Apteka.ru", "Ригла", "Горздрав", "Доктор Столетов", "Столички", "Wer.ru"]

urls_json = {
    'URLs':
        [
            {"drug_name":"Нурофен 200мг №10","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/nurofen_tab_po_200mg_%E2%84%9610_425-42151"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/no-shpa_tab_40mg_%E2%84%9660_s_dozatorom_805-5762"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/nimesulid-teva_tab_100mg_%E2%84%9620_7690-45277"},
            {"drug_name":"Спазмалгон №50","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/spazmalgon_tab_50_1042-104773"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/panadol_tab_rastv_500mg_%E2%84%9612_1096-6201"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/ketanov_tab_pokr_plo_10mg_%E2%84%96100_361-93258"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/fastum_gel_25_50g_282-9189"},
            {"drug_name":"Корвалол №20","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/korvalol_tab_%E2%84%9620_755-4092"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/novo-passit_r-r_dvn_prim_100ml_21-5771"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/afobazol_tab_10mg_%E2%84%9660_51-941"},
            {"drug_name":"Терафлю лимон №4","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/teraflyu_ot_grippa_i_prostudy_por_%E2%84%964_limon_6709-44845"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/strepsils_tab_drassas_%E2%84%9624_medlimon_1059-95205"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/geksoral_aer_02_40ml_6283-95179"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/nazoneks_spreji_naz_50mkgdoza_60doz_10g_6851-42480/description"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/pinosol_kapli_naz_10ml_10135-98833"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/sinekod_sirop_15mgml_100ml_396-7770"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/ambrobene_sirop_15mg5ml_100ml_77-579"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/atsts_200_tab_ship_200mg_%E2%84%9620_7531-43069"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/suprastin_tab_25mg_%E2%84%9620_7751-92459"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/klaritin_tab_10mg_10_208-3762"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/tavegil_tab_1mg_10_577-28826"},
            {"drug_name":"Фестал №20 драже","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/festal_drazhe_%E2%84%9620_1339-9265"},
            {"drug_name":"Мезим форте №20","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/mezim_forte_tab_po_20_8019-48654"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/smekta_por_dsusp_3g_pak_%E2%84%9610_vanil_506-7869"},
            {"drug_name":"Линекс капс №16","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/lineks_kaps_%E2%84%9616_3-4714"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/fosfalyugel_gel_dvn_prim_16g_pak_%E2%84%966_1363-45902"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/espumizan_kaps_40mg_%E2%84%9650_282-10297"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/imodium_tab_liofilizirov_2mg_%E2%84%9610_6383-93280"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/senade_tab_135mg_%E2%84%96500_1215-7648"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/bepanten_maz_5_30g_281-1119"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/baneotsin_maz_20g_255-1014"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Самсон Фарма","drug_url":"https://samson-pharma.ru/product/najiz_gel_1_20g_642-5524"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/2719/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/98/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/829/"},
            {"drug_name":"Спазмалгон №50","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/8535-3385/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/13205/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/obezbolivayushchie-zharoponizhayushchie-protivovospalitelnye-i-spazmoliticheskie-sredstva/1360/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-oporno-dvigatelnogo-apparata/11005/"},
            {"drug_name":"Корвалол №20","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-nervnoy-sistemy/sedativnye-sredstva/30056/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-nervnoy-sistemy/sedativnye-sredstva/17429/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-nervnoy-sistemy/anksiolitiki/12497/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/5950/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/1373/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/30400/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/gormonalnye-sredstva-i-ikh-antagonisty/7029/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/11226/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/12973/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/30460/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-prostudy-i-zabolevaniy-lor-organov/7529/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/protivoallergicheskie-sredstva/913/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/protivoallergicheskie-sredstva/1190/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/protivoallergicheskie-sredstva/11511/"},
            {"drug_name":"Фестал №20 драже","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/fermenty/12693/"},
            {"drug_name":"Мезим форте №20","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/fermenty/1336/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/sredstva-dlya-lecheniya-zabolevaniy-zheludka-i-dvenadtsatiperstnoy-kishki/117/"},
            {"drug_name":"Линекс капс №16","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/sredstva-dlya-vosstanovleniya-kishechnoy-mikroflory/9491/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/sredstva-dlya-lecheniya-zabolevaniy-zheludka-i-dvenadtsatiperstnoy-kishki/2899/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/vetrogonnye-sredstva/6711/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/protivodiareynye-sredstva/4910/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-zheludochno-kishechnogo-trakta/slabitelnye-sredstva/1701/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/dermatologicheskie-sredstva/ranozazhivlyayushchie-i-regeneriruyushchie-sredstva/11302/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/dermatologicheskie-sredstva/antibakterialnye-i-antisepticheskie-sredstva-dlya-naruzhnogo-primeneniya/15884/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Неофарм","drug_url":"http://neopharm.ru/drugs/lekarstvennye-sredstva/sredstva-dlya-lecheniya-zabolevaniy-oporno-dvigatelnogo-apparata/11272/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/protivovospalitelnye_sredstva/nurofen_200mg_n10_tab_pokrytye_obolochkoy_reckitt_benckiser.html"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/spazmolitiki/no-shpa_40mg_n60_tab_chinoin_pharmaceutical_and_chemical_work.html"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/protivovospalitelnye_sredstva/nimesulid-teva_100mg_n20_tab_teva.html"},
            {"drug_name":"Спазмалгон №50","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/spazmolitiki/spazmalgon_n50_tab_balkanfarma-dupnitsa_ad.html"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/protivovospalitelnye_sredstva/panadol_500mg_n12_tab_rastvorimye_famar_sa.html"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/bol/protivovospalitelnye_sredstva/ketanov_10mg_n100_tab_ranbaxy.html"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_oporno_dvigateln_apparata/obezbolivayushchie_protivovospalitelnye/fastum_25_50g_gel_dnaruzhnogo_primeneniya_amenarini_manufacturing_logistics.html"},
            {"drug_name":"Корвалол №20","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_nervnoy_sistemy/uspokaivayushchie/korvalol_n20_tab_farma_start_ooo.html"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_nervnoy_sistemy/uspokaivayushchie/novo-passit_100ml_r-r_dpriema_vnutr_ivax_pharmaceuticals_sro.html"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_nervnoy_sistemy/trankvilizatory/afobazol_10mg_n60_tab_farmstandart-leksredstva.html"},
            {"drug_name":"Терафлю лимон №4","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/dlya_snyatiya_simptomov_prostudy_i_grippa/teraflyu_limon_n4_poroshok_famar.html"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_boli_v_gorle/strepsils_n24_tab_drassasyvaniya_med-limon_reckitt_benckiser.html"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_boli_v_gorle/geksoral_02_40ml_aerozol_maknil_menyufekchuring.html"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/allergiya/gormonalnye_preparaty/nazoneks_50mkgdoza_60doz_sprey_nazalnyy_merk_sharp_i_doum.html"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_nasmorka/pinosol_10ml_kapli_nazalnye_zentiva_as.html"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_kashlya/sinekod_100ml_sirop_novartis_konsyumer_khels.html"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_kashlya/ambrobene_15mg5ml_100ml_sirop_merckle.html"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_orz_gripp_lor/ot_kashlya/atsts_200mg_n20_tab_shipuchie_sandoz_dd.html"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/allergiya/prochie_protivoallergicheskie_preparaty/suprastin_25mg_n20_tab_egis.html"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/allergiya/prochie_protivoallergicheskie_preparaty/klaritin_10mg_n10_tab_shering-plau_labo_nv.html"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/allergiya/prochie_protivoallergicheskie_preparaty/tavegil_1mg_n10_tab_famar.html"},
            {"drug_name":"Фестал №20 драже","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/fermenty/festal_n20_drazhe_aventis_pharma.html"},
            {"drug_name":"Мезим форте №20","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/fermenty/mezim_forte_n20_tab_berlin-khemi.html"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/diareya/smekta_3g_n10_poroshok_dprigotovleniya_suspenzii_dpriema_vnutr_vanil_bofur_ipsen_indastri.html"},
            {"drug_name":"Линекс капс №16","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/disbakterioz/lineks_n16_kaps_lek.html"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/antatsidy/fosfalyugel_16g_n6_gel_dpriema_vnutr_farmatis.html"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/meteorizm/espumizan_40mg_n50_kaps_berlin-khemi.html"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/diareya/imodium_2mg_n10_tab_liofilizirovannye_catalent_uk_swindon_zydis.html"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_zheludochno_kishechnye/slabitelnye/senade_135mg_n500_tab_tsipla_limited.html"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/ezhednevnyy_ukhod/ukhod_za_telom/uvlazhnyayushchie_vosstanavlivayushchie_sredstva/bepanten_5_30g_maz_grentsakh_produktsions_gmbkh_bayer_farma_ag.html"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_infektsionnye_i_parazitarnye/antibiotiki/baneotsin_20g_maz_sandoz_gmbh.html"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Асна","drug_url":"https://www.asna.ru/catalog/lekarstva/zabolevaniya_oporno_dvigateln_apparata/obezbolivayushchie_protivovospalitelnye/nayz_1_20g_gel_dnaruzhnogo_primeneniya_dr_reddys_laboratories_ltd.html"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id230733/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id209766/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id237654/"},
            {"drug_name":"Спазмалгон №50","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id218687/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id30356/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id29149/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id125718/"},
            {"drug_name":"Корвалол №20","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id210415/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id104049/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id211264/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id216868/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id20764/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id203487/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id215167/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id98612/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id212350/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id24493/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id23801/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id21756/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id20521/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id224166/"},
            {"drug_name":"Фестал №20 драже","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id117275/"},
            {"drug_name":"Мезим форте №20","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id22323/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id102476/"},
            {"drug_name":"Линекс капс №16","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id99148/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id243066/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id22351/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id259295/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id27833/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id24048/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id17654/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Eapteka","drug_url":"https://www.eapteka.ru/goods/id205880/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/nurofen-tab-p-o-200mg-10-48411/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/noshpa-tab-40mg-60-s-dozatorom-23121/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/nimesulidteva-tab-100mg-20-55490/"},
            {"drug_name":"Спазмалгон №50","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/spazmalgon-tab-50-38724/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/panadol-rastv-tab-500mg-12-7448/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/ketanov-tab-p-o-10mg-100-44140/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/fastum-gel-d-naruzh-prim-2-5-50g-26685/"},
            {"drug_name":"Корвалол №20","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/korvalol-tabl-n20-48595/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/novopassit-rr-d-priema-vnutr-100ml-32615/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/afobazol-tab-10mg-60-31288/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/tera-flju-limon-poroshok-n4-36952/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/strepsils-tabletki-d-rassas-med-limon-n24-25479/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/geksoral-aerozol-0-2-40ml-41814/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/nazoneks-sprej-nazal-doz-50mkg-60doz-38201/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/pinosol-kapli-nazal-10ml-17221/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/sinekod-sirop-1-5mg-ml-100ml-32722/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/ambrobene-sirop-15mg-5ml-flakon-100ml-1548/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/acc200-tabletki-shipuchie-200mg-n20-22001/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/suprastin-tab-25mg-20-9848/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/klaritin-tabl-10mg-n10-5058/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/tavegil-tabletki-1mg-n10-42169/"},
            {"drug_name":"Фестал №20 драже","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/festal-dr-20-31002/"},
            {"drug_name":"Мезим форте №20","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/mezim-forte-tab-p-o-20-43979/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/smekta-poroshok-d-suspenzija-paket-3g-n10-so-vkusom-vanili-60125/"},
            {"drug_name":"Линекс капс №16","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/lineks-kapsuly-n16-5926/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/fosfaljugel-gel-d-priema-vnutr-16g-6-47803/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/espumizan-kaps-40mg-50-36760/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/imodium-tab-liofilizirovannye-2mg-10-49435/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/senade-tabletki-n500-9281/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/bepanten-maz-d-naruzh-prim-5-30g-22162/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/baneocin-maz-20g-22163/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Аптека 36.6","drug_url":"https://apteka366.ru/p/najz-gel-1-20g-24044/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/nurofen-0-2-n10-tabl-p-o_53cf87eb37d42/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/no-shpa-004-n60-tabl-flakdozator_137387/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/nimesulid-teva-0-1-n20-tabl-_54742f255031f/"},
            {"drug_name":"Спазмалгон №50","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/spazmalgon-n50-tabl_57767288364c1/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/panadol-05-n12-tabl-rastv_131946/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/ketanov-0-01-n100-tabl-p-o_53fc86f706617/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/fastum-25-500-gel_132285/"},
            {"drug_name":"Корвалол №20","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/korvalol-n20-tabl_143124/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/novo-passit-100ml-flak-r-r-d-priema-vnutr_577f5bae0ee64/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/afobazol-001-n60-tabl_80518/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/teraflu-ot-grippaprostudy-n4-pak_148256/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/strepsils-medovo-limonnyi-n24-tabl_135888/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/geksoral-02-400-aerozol_151545/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/nazoneks-50mkg-doza-60-doz-naz-sprey_54b62cdc6cec5/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/pinosol-10ml-kapli_56ab0be476343/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/sinekod-00015ml-100ml-flak-sirop_132554/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/ambrobene-00155ml-100ml-sirop_139060/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/atsts-200-n20-ship-tabl_54f82aa99a565/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/suprastin-0-025-n20-tabl_549ab25566393/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/klaritin-001-n10-tabl_93346/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/tavegil-0001-n10-tabl_152826/"},
            {"drug_name":"Фестал №20 драже","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/festal-n20-drazhe_5511354d41451/"},
            {"drug_name":"Мезим форте №20","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/mezim-forte-n20-tabl-p-o_53e222c7bfc1a/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/smekta-30-n10-por-dsusp-vanil_89711/"},
            {"drug_name":"Линекс капс №16","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/lineks-n16-kaps_84291/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/fosfalyugel-16-0-n6-pak-_55d46cb868203/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/espumizan-0-04-n50-kaps_55674647e680e/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/imodium-0-002-n10-tabl-liofiliz-_56d90aeb0d3d0/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/senade-n500-tabl_91010/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/bepanten-5-300-maz_131002/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/baneotsin-20-0-maz_53db88e1bad0c/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Apteka.ru","drug_url":"https://apteka.ru/catalog/naiz-1-200-gel_141075/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/98539_nurofen_tab_200mg_n10/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/13345_no-shpa_upakovka_push_ap_tab_40mg_n60/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/105591_nimesulid-teva_tab_100mg_n20/"},
            {"drug_name":"Спазмалгон №50","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/83562_spazmalgon_tab_n50/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1413_panadol_tabrastv_500mg_n12/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/910_ketanov_tabpo_10mg_n100/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1925_fastum_gel_25p_50g/"},
            {"drug_name":"Корвалол №20","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/14413_korvalol_tab_n20/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1322_novo-passit_r-r_dpriema_vnutr_100ml/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/4474347_afobazol_tab_10mg_n60/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/77067_teraflyu_ot_grippa_i_prostudy_limon_pordprigr-ra_n4/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1737_strepsils_medlimon_ledentsy_n24/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/513_geksoral_aer_02p_40ml/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/81667_nazoneks_sprey_naz_50_mkg_60doz/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1467_pinosol_kapli_naz_10ml/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/32923_sinekod_sirop_100ml/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/81_ambrobene_sirop_15mg5ml_100ml/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/99549_atsts_tabship_200mg_n20/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1780_suprastin_tab_25mg_n20/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/921_klaritin_tab_10mg_n10/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/94032_tavegil_tab_1mg_n10/"},
            {"drug_name":"Фестал №20 драже","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1955_festal_drazhe_n20/"},
            {"drug_name":"Мезим форте №20","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1144_mezim_forte_tabpo_n20/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/1699_smekta_pordprigsusp_3g_n10/"},
            {"drug_name":"Линекс капс №16","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/3030_lineks_kaps_n16/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/100094_fosfalyugel_gel_dpriema_vnutr_n6/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/75845_espumizan_kaps_40mg_n50/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/100718_imodium_tabliof_2mg_n10/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/2379_senade_tab_n500/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/260_bepanten_maz_5p_30g/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/3167_baneotsin_maz_20g/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Ригла","drug_url":"http://www.rigla.ru/shop/item/7852_nayz_gel_1p_20g/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/nurofen-tab-p-o-200mg-10-48411/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/noshpa-tabl-flak-s-dozatorom-40mg-n60-23121/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/nimesulid-teva-tabl-100mg-n20-55490/"},
            {"drug_name":"Спазмалгон №50","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/spazmalgon-tabl-n50-38724/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/panadol-tabl-rastvor-500mg-n12-7448/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/ketanov-tabl-p-o-10mg-n100-44140/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/fastum-gel-2-5-50g-26685/"},
            {"drug_name":"Корвалол №20","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/korvalol-tabl-n20-24475/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/novopassit-rr-d-priema-vnutr-100ml-32615/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/afobazol-tabl-10mg-n60-31288/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/tera-flju-limon-por-n4-36952/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/strepsils-tabl-d-rassas-med-limon-n24-25479/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/geksoral-aeroz-0-2-40ml-41814/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/nazoneks-sprej-naz-doz-50mkg-60doz-38201/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/pinosol-kapli-naz-10ml-17221/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/sinekod-sirop-1-5mg-ml-100ml-32722/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/ambrobene-sirop-15mg-5ml-flakon-100ml-1548/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/acc200-tabl-shipuch-200mg-n20-22001/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/suprastin-tabl-25mg-n20-9848/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/klaritin-tabl-10mg-n10-5058/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/tavegil-tabl-1mg-n10-42169/"},
            {"drug_name":"Фестал №20 драже","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/festal-drazhe-n20-31002/"},
            {"drug_name":"Мезим форте №20","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/mezim-forte-tabl-p-o-n20-6206/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/smekta-por-d-susp-paket-3g-n10-so-vkusom-vanili-60125/"},
            {"drug_name":"Линекс капс №16","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/lineks-kaps-n16-5926/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/fosfaljugel-susp-paket-16g-n6-47803/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/espumizan-kaps-40mg-n50-36760/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/imodium-tabl-liofilizirovannye-2mg-n10-49435/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/senade-tabl-n500-9281/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/bepanten-maz-5-30g-2308/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/baneocin-maz-20g-22163/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Горздрав","drug_url":"https://gorzdrav.org/p/najz-gel-1-20g-24044/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/nurofen-tab-p-o-200mg-10/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/no-shpa-tab-40mg-64/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/nimesulid-tab-100mg-20/"},
            {"drug_name":"Спазмалгон №50","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/spazmalgon-tab-50/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/panadol-tab-rastvor-500mg-12_1/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/ketanov-tab-p-p-o-10mg-100-blister/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/fastum-gel-d-naruzhn-prim-2-5-tuba-50g/"},
            {"drug_name":"Корвалол №20","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/korvalol-tab-20/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/novo-passit-r-r-d-priema-vnutr-fl-100-ml/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/afobazol-tab-10mg-60_1/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/teraflyu-ot-grippa-i-prostudy-por-d-prig-r-ra-d-priema-vnutr-limon-4/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/strepsils-medovo-limonnyy-tb-n24/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/geksoral-aeroz-d-mestn-prim-0-2-aeroz-40-ml/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/nazoneks-naz-sprey-50mkg-doza-60doz-n1_1/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/pinosol-kapli-10ml/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/sinekod-sirop-1-5-mg-ml-fl-100-ml-s-mern-stak/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/ambrobene-sirop-15-mg-5-ml-fl-100-ml-s-mern-stak/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/atsts-200-tabl-ship-200-mg-tuba-20/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/suprastin-tb-25mg-n20/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/klaritin-tab-10mg-10/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/tavegil-tab-1mg-10/"},
            {"drug_name":"Фестал №20 драже","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/festal-drazhe-n20_3/"},
            {"drug_name":"Мезим форте №20","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/mezim-forte-tabl-p-o-20_2/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/smekta-vanil-por-3-gr-n10/"},
            {"drug_name":"Линекс капс №16","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/lineks-por-liof-kaps-16/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/fosfalyugel-gel-16g-n6/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/espumizan-kaps-40mg-50/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/imodium-tabl-liof-2mg-10/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/senade-tb-13-5mg-n500/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/bepanten-maz-d-naruzhn-prim-5-tuba-30g-1/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/baneotsin-maz-d-naruzhn-prim-tuba-20g-1/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Доктор Столетов","drug_url":"https://stoletov.ru/catalog/product/nayz-gel-d-naruzhn-prim-1-tuba-20g/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/2719/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/98/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/829/"},
            {"drug_name":"Спазмалгон №50","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/8535/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/13205/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/1360/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/11005/"},
            {"drug_name":"Корвалол №20","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/30056/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/17429/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/12497/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/5950/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/1373/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/30400/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/7029/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/11226/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/12973/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/30460/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/7529/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/913/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/1190/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/11511/"},
            {"drug_name":"Фестал №20 драже","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/12693/"},
            {"drug_name":"Мезим форте №20","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/1336/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/117/"},
            {"drug_name":"Линекс капс №16","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/9491/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/2899/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/6711/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/4910/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/1701/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/11302/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/15884/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Столички","drug_url":"https://stolichki.ru/drugs/11272/"},
            {"drug_name":"Нурофен 200мг №10","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/nurofen_200mg_n10_tab_pokrytye_obolochkoi/"},
            {"drug_name":"Но-шпа 40мг №60","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/no_shpa60/"},
            {"drug_name":"Нимесулид 100мг №20","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/nimesulid_100mg_n20_tab_teva/"},
            {"drug_name":"Спазмалгон №50","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/spazmalgon_n50_tab__145/"},
            {"drug_name":"Панадол 500мг №12 таб раств","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/panadol_n12_rastv_tab_/"},
            {"drug_name":"Кетанов 10мг №100","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/ketanov_10mg_n100_tab_/"},
            {"drug_name":"Фастум гель 2,5% 50г","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/fastum_gel50/"},
            {"drug_name":"Корвалол №20","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/korvalol_tabletki_20_sht_farma_start/"},
            {"drug_name":"Ново-пассит 100мл","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/novo_passit_rastvor_100ml/"},
            {"drug_name":"Афобазол 10мг №60","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/afobazol_10mg_n60_tab_/"},
            {"drug_name":"Терафлю лимон №4","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/teraflyu_n4_poroshok_limon/"},
            {"drug_name":"Стрепсилс мед лимон №24","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/strepsils_n24_tab_d_rassasyvanija_med_limon_29/"},
            {"drug_name":"Гексорал 0,2% 40мл","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/geksoral_02_40ml_ayerozol_127/"},
            {"drug_name":"Назонекс 50мкг 60доз","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/nazoneks_50mkg_doza_60doz_naz_sprei/"},
            {"drug_name":"Пиносол капли 10мл","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/pinosol_10ml_kapli_114/"},
            {"drug_name":"Синекод 1,5мг 100мл сироп","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/sinekod_sirop_100ml/"},
            {"drug_name":"Амбробене сироп 15мг/5мл 100мл","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/ambrobene_15mg_5ml_100ml_sirop_133/"},
            {"drug_name":"АЦЦ 200мг №20 таб шип","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/acc_200mg_ship_tab_n20/"},
            {"drug_name":"Супрастин 25мг №20","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/suprastin/"},
            {"drug_name":"Кларитин 10мг №10","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/klaritin10/"},
            {"drug_name":"Тавегил 1мг №10","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/tavegil_1mg_n10_tab__115/"},
            {"drug_name":"Фестал №20 драже","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/festal_n20_drazhe/"},
            {"drug_name":"Мезим форте №20","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/mezim_forte_n20_tab__177/"},
            {"drug_name":"Смекта 3г №10 ваниль","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/smekta_3g_n10_por_/"},
            {"drug_name":"Линекс капс №16","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/lineks_n16_kaps__32/"},
            {"drug_name":"Фосфалюгель 16г №6","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/fosfalyugel_160_6/"},
            {"drug_name":"Эспумизан 40мг №50","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/yespumizan_n50_kaps__161/"},
            {"drug_name":"Имодиум 2мг №10 лиоф","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/imodium_tab_liof_2_mg_20/"},
            {"drug_name":"Сенаде 13,5мг №500","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/senade_n500_tab__157/"},
            {"drug_name":"Бепантен мазь 5% 30г","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/bepanten_maz_5_30g/"},
            {"drug_name":"Банеоцин мазь 20г","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/baneocin_20g_maz/"},
            {"drug_name":"Найз гель 1% 20г","store_name":"Wer.ru","drug_url":"https://wer.ru/catalog/naiz_gel_1_20g/"}
        ]
}
